import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { chmodSync, cpSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const [output, ...extra] = process.argv.slice(2);
if (!output || extra.length || process.platform !== "linux") throw new Error("usage (Linux): node scripts/distribution/linux.mjs <bundle-directory>");
const directory = resolve(output);
const build = JSON.parse(readFileSync(resolve(directory, "bundle.json")));
if (build.target !== `linux-${process.arch}`) throw new Error("Linux bundle architecture mismatch");
const arch = process.arch === "x64" ? "amd64" : "arm64";
const rpmArch = process.arch === "x64" ? "x86_64" : "aarch64";
const root = resolve(directory, "deb");
mkdirSync(resolve(root, "usr/lib"), { recursive: true });
cpSync(resolve(directory, "stage"), resolve(root, "usr/lib/octonodes"), { recursive: true });
mkdirSync(resolve(root, "usr/bin"), { recursive: true });
writeFileSync(resolve(root, "usr/bin/octonodes"), '#!/bin/sh\nexec /usr/lib/octonodes/bin/octonodes "$@"\n');
chmodSync(resolve(root, "usr/bin/octonodes"), 0o755);
mkdirSync(resolve(root, "DEBIAN"));
writeFileSync(resolve(root, "DEBIAN/control"), `Package: octonodes\nVersion: ${build.version}\nArchitecture: ${arch}\nMaintainer: Octonode <support@octonodes.com>\nSection: devel\nPriority: optional\nDepends: libc6 (>= 2.28), libstdc++6\nDescription: Octonode API and plugin development CLI\n Includes its own Node 24 runtime.\n`);
const deb = `octonodes_${build.version}_${arch}.deb`;
execFileSync("dpkg-deb", ["--root-owner-group", "--build", root, resolve(directory, deb)], { stdio: "inherit" });
const rpmRoot = resolve(directory, "rpmbuild");
for (const folder of ["BUILD", "BUILDROOT", "RPMS", "SOURCES", "SPECS", "SRPMS"]) mkdirSync(resolve(rpmRoot, folder), { recursive: true });
const spec = `Name: octonodes\nVersion: ${build.version}\nRelease: 1\nSummary: Octonode API and plugin development CLI\nLicense: MIT AND BSD-3-Clause\nURL: https://github.com/nivdoron1/octonode-devtools\nBuildArch: ${rpmArch}\nAutoReqProv: no\nRequires: glibc >= 2.28, libstdc++\n%description\nOctonode CLI with a bundled Node 24 runtime.\n%install\nmkdir -p %{buildroot}/usr/lib %{buildroot}/usr/bin\ncp -a "${resolve(root, "usr/lib/octonodes")}" %{buildroot}/usr/lib/\ncp "${resolve(root, "usr/bin/octonodes")}" %{buildroot}/usr/bin/\n%files\n/usr/lib/octonodes\n/usr/bin/octonodes\n`;
writeFileSync(resolve(rpmRoot, "SPECS/octonodes.spec"), spec);
execFileSync("rpmbuild", ["-bb", "--define", `_topdir ${rpmRoot}`, "--define", "__os_install_post %{nil}", resolve(rpmRoot, "SPECS/octonodes.spec")], { stdio: "inherit" });
const rpms = readdirSync(resolve(rpmRoot, "RPMS", rpmArch)).filter((file) => file.endsWith(".rpm"));
if (rpms.length !== 1) throw new Error("Expected exactly one RPM");
cpSync(resolve(rpmRoot, "RPMS", rpmArch, rpms[0]), resolve(directory, rpms[0]));
for (const file of [deb, rpms[0]]) build.assets.push({ file, sha256: createHash("sha256").update(readFileSync(resolve(directory, file))).digest("hex") });
writeFileSync(resolve(directory, "bundle.json"), JSON.stringify(build, null, 2) + "\n");
