// Generated from packages/plugin-runtime/src/definitions/compiler/catalog.ts. Do not edit; run the Octonode SDK sync.
import * as ts from "typescript";
import { existsSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { relative, resolve } from "node:path";
import { createHash } from "node:crypto";
import { DEFINITION_FILES, NODES_FILENAME } from "./constants";

/** Discovery is static: importing application modules would execute user code. */
export function generateNodeCatalog(root: string, files?: readonly string[], check = false): string {
  root = realpathSync(root);
  const inventory = resolve(root, NODES_FILENAME);
  let npmInventory: string | undefined;
  if (existsSync(inventory)) {
    if (realpathSync(inventory) !== inventory) throw new Error(`${NODES_FILENAME} must not be a symlink`);
    const current = readFileSync(inventory, "utf8");
    const prefix = ["// Generated npm inventory: ", "// Generated workflow inventory: "].find((prefix) =>
      current.startsWith(prefix),
    );
    if (prefix) {
      const newline = current.indexOf("\n");
      const body = current.slice(newline + 1);
      if (current.slice(prefix.length, newline) !== createHash("sha256").update(body).digest("hex"))
        throw new Error(`${NODES_FILENAME} was edited; regenerate from the original package or workflow`);
      if (prefix === "// Generated workflow inventory: ") return current;
      npmInventory = body;
    }
  }
  const configPath = existsSync(resolve(root, "tsconfig.json")) ? resolve(root, "tsconfig.json") : undefined;
  const config = configPath ? ts.readConfigFile(configPath, ts.sys.readFile) : { config: {} };
  if (config.error) throw new Error(ts.flattenDiagnosticMessageText(config.error.messageText, "\n"));
  const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, root);
  const error = parsed.errors.find((error) => error.code !== 18003);
  if (error) throw new Error(ts.flattenDiagnosticMessageText(error.messageText, "\n"));
  const paths = (files ?? parsed.fileNames)
    .map((file) => resolve(root, file))
    .filter((file) => {
      const path = relative(root, file).replaceAll("\\", "/");
      return (
        !path.startsWith("../") &&
        !path.split("/").some((part) => part === "node_modules" || part === "dist" || part.startsWith(".")) &&
        !DEFINITION_FILES.includes(path) &&
        !/\.d\.[cm]?ts$/.test(path) &&
        /\.[cm]?ts$/.test(path)
      );
    })
    .sort();
  // Inventory needs callable export identities only; definition compilation checks full types.
  const program = ts.createProgram(paths, {
    ...parsed.options,
    noEmit: true,
    noLib: true,
    noResolve: true,
    types: [],
    skipLibCheck: true,
  });
  const checker = program.getTypeChecker();
  const entries: { path: string; name: string }[] = [];
  for (const path of paths) {
    const source = program.getSourceFile(path);
    const module = source && checker.getSymbolAtLocation(source);
    if (!module) continue;
    for (const exported of checker.getExportsOfModule(module).sort((a, b) => a.name.localeCompare(b.name))) {
      const symbol = exported.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(exported) : exported;
      const declaration = symbol.valueDeclaration;
      if (!declaration || resolve(declaration.getSourceFile().fileName) !== path) continue;
      if (!checker.getTypeOfSymbolAtLocation(symbol, declaration).getCallSignatures().length) continue;
      entries.push({ path: relative(root, path).replaceAll("\\", "/"), name: exported.name });
    }
  }
  const counts = new Map<string, number>();
  for (const entry of entries) counts.set(entry.name, (counts.get(entry.name) ?? 0) + 1);
  const key = (entry: (typeof entries)[number]) =>
    counts.get(entry.name) === 1
      ? entry.name
      : `${entry.name}_${createHash("sha256").update(entry.path).digest("hex").slice(0, 8)}`;
  let text =
    "// Generated by Octonode. Do not edit.\n" +
    entries
      .map(
        (entry, index) =>
          `import { ${entry.name} as node${index} } from ${JSON.stringify(
            "./" +
              entry.path
                .replace(/\.ts$/, ".js")
                .replace(/\.mts$/, ".mjs")
                .replace(/\.cts$/, ".cjs"),
          )};`,
      )
      .join("\n") +
    "\nexport const nodes = {\n" +
    entries.map((entry, index) => `  ${JSON.stringify(key(entry))}: node${index},`).join("\n") +
    "\n} as const;\n";
  if (npmInventory) {
    const source = ts.createSourceFile(inventory, npmInventory, ts.ScriptTarget.Latest, true);
    const declarations = source.statements
      .filter(ts.isVariableStatement)
      .flatMap((statement) => [...statement.declarationList.declarations]);
    const declaration = declarations.find((item) => ts.isIdentifier(item.name) && item.name.text === "nodes");
    const initializer = declaration?.initializer;
    const object = initializer && ts.isAsExpression(initializer) ? initializer.expression : initializer;
    if (!object || !ts.isObjectLiteralExpression(object)) throw new Error("Invalid npm inventory; regenerate it");
    const adapters = object.properties.filter(
      (item): item is ts.PropertyAssignment => ts.isPropertyAssignment(item) && ts.isCallExpression(item.initializer),
    );
    const names = new Set(
      adapters.map((item) =>
        ts.isStringLiteral(item.name) || ts.isIdentifier(item.name) ? item.name.text : item.name.getText(source),
      ),
    );
    if (entries.some((entry) => names.has(key(entry))))
      throw new Error("Local and npm inventory names collide; rename the local export");
    const imports = source.statements
      .filter(ts.isImportDeclaration)
      .filter(
        (statement) => ts.isStringLiteral(statement.moduleSpecifier) && !statement.moduleSpecifier.text.startsWith("."),
      )
      .map((statement) => statement.getText(source))
      .join("\n");
    if (!entries.length && object.properties.length === adapters.length) text = npmInventory;
    else
      text =
        imports +
        "\n" +
        text
          .replace("// Generated by Octonode. Do not edit.\n", "")
          .replace(
            "export const nodes = {\n",
            "export const nodes = {\n" + adapters.map((item) => item.getText(source) + ",").join("\n") + "\n",
          );
    text = `// Generated npm inventory: ${createHash("sha256").update(text).digest("hex")}\n${text}`;
  }
  const output = resolve(root, NODES_FILENAME);
  if (existsSync(output) && realpathSync(output) !== output) throw new Error(`${NODES_FILENAME} must not be a symlink`);
  if (check) {
    if (!existsSync(output) || readFileSync(output, "utf8") !== text)
      throw new Error(`${NODES_FILENAME} is stale; regenerate the node inventory`);
  } else if (!existsSync(output) || readFileSync(output, "utf8") !== text) writeFileSync(output, text);
  return text;
}
