// Generated from packages/ui-extensions/src/app/OctonodeAppProvider/AppAccessScreen/constants.ts. Do not edit; run the Octonode SDK sync.
// Inline, scoped styles keep the public React SDK independent of host CSS and asset loaders.
export const ACCESS_SCREEN_CSS = `
.octo-access{--octo-ink:#252536;--octo-muted:#636374;--octo-coral:#ff765f;box-sizing:border-box;min-height:100svh;background:#f7f8fc;color:var(--octo-ink);font-family:"Avenir Next",Avenir,"Segoe UI",sans-serif;font-size:16px;line-height:1.5;padding:0 48px;isolation:isolate}
.octo-access *{box-sizing:border-box}.octo-access a{color:inherit;text-decoration:none}.octo-access a:focus-visible{outline:3px solid #af3e29;outline-offset:5px}.octo-access a:hover{text-decoration:underline}
.octo-access-header,.octo-access-footer{max-width:1120px;margin:auto;display:flex;justify-content:space-between;align-items:center;gap:24px}.octo-access-header{height:100px;border-bottom:1px solid #e3e5ee}.octo-access-brand{display:flex;align-items:center;gap:10px;font-size:23px;font-weight:750;letter-spacing:-1px}.octo-access-brand img{width:36px;height:36px}.octo-access a.octo-access-guide{font-size:14px;color:var(--octo-muted);display:flex;align-items:center;gap:8px}
.octo-access-main{max-width:1120px;min-height:calc(100svh - 185px);margin:auto;display:grid;grid-template-columns:1.05fr 1fr;align-items:center;gap:70px;padding:72px 0}.octo-access-copy{max-width:520px}.octo-access-status{display:inline-flex;align-items:center;gap:8px;margin:0 0 24px;padding:6px 11px;border:1px solid #dedeea;background:#eeeff6;border-radius:6px;font-size:12px;font-weight:600;color:#515164}.octo-access-status svg{width:14px;height:14px}.octo-access h1{margin:0;font-size:clamp(40px,4.3vw,62px);font-weight:650;letter-spacing:-2.8px;line-height:1.09;text-wrap:balance}.octo-access-description{max-width:430px;margin:24px 0 30px;font-size:17px;line-height:1.75;color:var(--octo-muted)}.octo-access-actions{display:flex;align-items:center;gap:23px;flex-wrap:wrap}.octo-access a.octo-access-primary{display:inline-flex;align-items:center;justify-content:center;gap:12px;min-height:50px;padding:13px 21px;border-radius:9px;background:var(--octo-ink);color:#fff;font-size:14px;font-weight:650;box-shadow:0 4px 0 #25253612}.octo-access a.octo-access-primary:hover{background:#404056;text-decoration:none}.octo-access-secondary{font-size:14px;font-weight:600}.octo-access-hint{display:flex;align-items:flex-start;gap:9px;max-width:415px;margin:27px 0 0;color:var(--octo-muted);font-size:12px;line-height:1.65}.octo-access-hint svg{flex:none;width:15px;height:15px;margin-top:2px}
.octo-access-visual{position:relative;aspect-ratio:1;display:grid;place-items:center}.octo-access-orbit{position:absolute;width:87%;aspect-ratio:1;border:1px solid #dfe2ee;border-radius:50%}.octo-access-orbit::before{content:"";position:absolute;inset:42px;border:1px dashed #dfe2ee;border-radius:50%}.octo-access-orbit::after{content:"";position:absolute;width:10px;height:10px;border-radius:50%;background:#b2b7cf;top:13%;left:13%;box-shadow:285px 240px 0 #ffb7a8}.octo-access-workspace{position:relative;transform:rotate(-5deg);width:90%;max-width:405px;background:#fff;border:1px solid #dee1ed;border-radius:14px;box-shadow:0 24px 65px #373e6510;overflow:hidden}.octo-access-window{height:39px;border-bottom:1px solid #eceef4;display:flex;align-items:center;gap:5px;padding:0 16px;background:#fafbfe}.octo-access-window i{width:6px;height:6px;border-radius:50%;background:#d3d7e3}.octo-access-window span{margin:auto;color:#5e6578;font-size:10px}.octo-access-window b{width:22px}.octo-access-body{padding:25px 24px 22px}.octo-access-workspace-title{font-size:13px;font-weight:650;display:flex;align-items:center;gap:9px}.octo-access-workspace-title img{width:23px;height:23px;border-radius:6px}.octo-access-skeleton{height:6px;width:42%;margin-top:11px;border-radius:3px;background:#eceef5}.octo-access-flow{display:flex;align-items:center;margin:29px 0}.octo-access-node{width:62px;height:61px;display:grid;place-items:center;background:#f4f5fa;border:1px solid #e1e4ef;border-radius:11px}.octo-access-node svg{width:23px;height:23px;color:#9ca3bc}.octo-access-node.active{background:#fff0eb;border-color:#ffc4b7}.octo-access-node.active svg{color:#bd4832}.octo-access-wire{height:1px;background:#d9ddec;flex:1}.octo-access-placeholder{display:flex;gap:8px;margin-top:12px}.octo-access-placeholder i{height:6px;width:35%;border-radius:3px;background:#eceef5}.octo-access-placeholder i+ i{width:20%}.octo-access-lock{position:absolute;bottom:10%;right:0;width:76px;height:76px;display:grid;place-items:center;border:7px solid #f7f8fc;border-radius:22px;background:#fff0eb;transform:rotate(7deg);box-shadow:0 8px 25px #373e650a}.octo-access-lock svg{width:29px;height:29px;color:#bd4832}.octo-access-caption{position:absolute;bottom:0;margin:0;font-size:12px;color:#5e6578;text-align:center}
.octo-access-footer{min-height:85px;border-top:1px solid #e3e5ee;color:#5e6578;font-size:12px}.octo-access-footer p{margin:0}.octo-access-footer a{padding:10px 0}.octo-access-connecting .octo-access-status svg{animation:octo-turn 2s linear infinite}@keyframes octo-turn{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){.octo-access-connecting .octo-access-status svg{animation:none}}
@media(max-width:850px){.octo-access{padding:0 28px}.octo-access-main{gap:25px}.octo-access h1{font-size:44px}.octo-access-visual{min-width:0}.octo-access-body{padding:18px}.octo-access-orbit::after{box-shadow:none}}@media(max-width:650px){.octo-access{padding:0 24px}.octo-access-header{height:80px}.octo-access-brand{font-size:21px}.octo-access-main{grid-template-columns:1fr;gap:45px;padding:48px 0 40px}.octo-access-copy{max-width:480px}.octo-access h1{font-size:clamp(38px,8vw,46px);letter-spacing:-2px}.octo-access-description{font-size:16px}.octo-access-visual{width:100%;max-width:390px;margin:auto;aspect-ratio:auto;min-height:340px;padding-bottom:40px}.octo-access-footer{align-items:flex-start;padding:22px 0;min-height:80px;font-size:11px}.octo-access a.octo-access-guide{font-size:12px}.octo-access-caption{font-size:11px}.octo-access-lock{right:4%}}
@media(forced-colors:active){.octo-access,.octo-access *{color:CanvasText!important}.octo-access a,.octo-access a *{color:LinkText!important}}
`;
export const OCTONODE_LOGO =
  "data:image/svg+xml," +
  encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none">\n  <title>Octonode</title>\n  <rect width="64" height="64" rx="16" fill="#181721"/>\n  <path d="M24 10h16l14 14v16L40 54H24L10 40V24Z" stroke="#FF765F" stroke-linejoin="round" stroke-width="3.5"/>\n  <path d="m21 24 11 8 11-8M32 32v13" stroke="#FF765F" stroke-linecap="round" stroke-linejoin="round" stroke-width="3"/>\n  <g fill="#FF765F"><circle cx="21" cy="24" r="3"/><circle cx="43" cy="24" r="3"/><circle cx="32" cy="32" r="4"/><circle cx="32" cy="45" r="3"/></g>\n</svg>\n',
  );
